"""Add ServiceHealth and DashboardLayout models, Slack fields  # """Add ServiceHealth and DashboardLayout models, Slack fields
  # blank line
Revision ID: f61363315609  # Revision ID: f61363315609
Revises:   # Revises:
Create Date: 2025-11-25 17:57:04.258013  # Create Date: 2025-11-25 17:57:04.258013
  # blank line
"""  # """
from alembic import op  # from alembic import op
import sqlalchemy as sa  # import sqlalchemy as sa
  # blank line
  # blank line
# revision identifiers, used by Alembic.  # # revision identifiers, used by Alembic.
revision = 'f61363315609'  # revision = 'f61363315609'
down_revision = None  # down_revision = None
branch_labels = None  # branch_labels = None
depends_on = None  # depends_on = None
  # blank line
  # blank line
def upgrade():  # def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###  # # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:  # with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_sent', sa.Boolean(), nullable=True))  # batch_op.add_column(sa.Column('slack_sent', sa.Boolean(), nullable=True))
  # blank line
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:  # with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_slack', sa.Boolean(), nullable=True))  # batch_op.add_column(sa.Column('notify_slack', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))  # batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
  # blank line
    # ### end Alembic commands ###  # # ### end Alembic commands ###
  # blank line
  # blank line
def downgrade():  # def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###  # # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:  # with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_column('updated_at')  # batch_op.drop_column('updated_at')
        batch_op.drop_column('notify_slack')  # batch_op.drop_column('notify_slack')
  # blank line
    with op.batch_alter_table('alert_history', schema=None) as batch_op:  # with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_column('slack_sent')  # batch_op.drop_column('slack_sent')
  # blank line
    # ### end Alembic commands ###  # # ### end Alembic commands ###
