"""Add ServiceHealth and DashboardLayout models, Slack fields

Revision ID: f61363315609
Revises: 
Create Date: 2025-11-25 17:57:04.258013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61363315609'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_sent', sa.Boolean(), nullable=True))

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_slack', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notify_slack')

    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_column('slack_sent')

    # ### end Alembic commands ###
